version: 2
project_name: auto-mr
before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -X main.version={{.Version}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: windows
        goarch: arm
        goarm: "7"
      - goos: windows
        goarch: arm
        goarm: "6"

archives:
  - name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    formats: ['binary']

checksum:
  # https://goreleaser.com/customization/checksum/
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - homepage: 'https://github.com/sgaunet/auto-mr'
    description: ''
    directory: Formula
    commit_author:
      name: sgaunet
      email: 1552102+sgaunet@users.noreply.github.com
    repository:
      owner: sgaunet
      name: homebrew-tools
      # Token with 'repo' scope is required for pushing to a different repository
      token: '{{ .Env.HOMEBREW_TAP_TOKEN }}'
    url_template: 'https://github.com/sgaunet/auto-mr/releases/download/{{ .Tag }}/{{ .ArtifactName }}'
    install: |
      bin.install "{{ .ArtifactName }}" => "auto-mr"
    test: |
      system "#{bin}/auto-mr", "--help"